<<<<<<< HEAD

=======
>>>>>>> 2778019517a0433caf58eb6181fb0d0fb37a26d4
#General mod settings
[general]
	#logging
	useLoggingLog = true
	#-
	useLoggingDebug = false
	#-
	useLoggingError = true
<<<<<<< HEAD

=======
>>>>>>> 2778019517a0433caf58eb6181fb0d0fb37a26d4
