<<<<<<< HEAD

=======
>>>>>>> 2778019517a0433caf58eb6181fb0d0fb37a26d4
#Recipes and Integrations
[recipes]
	#Enable vanilla-style recipes.
	vanillaRecipes = true
<<<<<<< HEAD

=======
>>>>>>> 2778019517a0433caf58eb6181fb0d0fb37a26d4
