# Convert emoji sent from Discord to their names. For example, "😃" will be converted to ":smiley:"
# Can be used for correct compatibility with the Emojiful mod
translateUnicodeEmojisToTextAliases = false
# Maximum number of messages in the chat.
# When the number of messages exceeds this value, old messages are automatically deleted.
# By default, this value is 100 in the vanilla game.
#Range: > 20
maxChatHistory = 500

