
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.stone_type]

		[types.stone_type.create]
			limestone = true
			asurine = true
			crimsite = true
			ochrum = true
			veridium = true
			scoria = true
			scorchia = true

		[types.stone_type.spelunkery]
			nephrite = true

	[types.wood_type]

		[types.wood_type.would]
			willow = true
			baobab = true
			ebony = true
			fir = true
			pine = true
			cedar = true
			mahogany = true
			azalea = true
			palm = true
			maple = true
			aspen = true
			walnut = true

		[types.wood_type.iceandfire]
			dreadwood = true

		[types.wood_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

	[types.leaves_type]

		[types.leaves_type.twilightforest]
			beanstalk = true
			thorn = true
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			rainbow_oak = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.leaves_type.chipped]
			apple_acacia = true
			cherry_acacia = true
			dead_acacia = true
			frosted_acacia = true
			golden_acacia = true
			golden_cherry_acacia = true
			magenta_flower_acacia = true
			orange_acacia = true
			red_acacia = true
			white_flower_acacia = true
			apple_birch = true
			cherry_birch = true
			dead_birch = true
			frosted_birch = true
			golden_birch = true
			golden_cherry_birch = true
			magenta_flower_birch = true
			orange_birch = true
			red_birch = true
			white_flower_birch = true
			apple_dark_oak = true
			cherry_dark_oak = true
			dead_dark_oak = true
			frosted_dark_oak = true
			golden_dark_oak = true
			golden_cherry_dark_oak = true
			magenta_flower_dark_oak = true
			orange_dark_oak = true
			red_dark_oak = true
			white_flower_dark_oak = true
			apple_jungle = true
			cherry_jungle = true
			dead_jungle = true
			frosted_jungle = true
			golden_jungle = true
			golden_cherry_jungle = true
			magenta_flower_jungle = true
			orange_jungle = true
			red_jungle = true
			white_flower_jungle = true
			apple_oak = true
			cherry_oak = true
			dead_oak = true
			frosted_oak = true
			golden_oak = true
			golden_cherry_oak = true
			magenta_flower_oak = true
			orange_oak = true
			red_oak = true
			white_flower_oak = true
			apple_spruce = true
			cherry_spruce = true
			dead_spruce = true
			frosted_spruce = true
			golden_spruce = true
			golden_cherry_spruce = true
			magenta_flower_spruce = true
			orange_spruce = true
			red_spruce = true
			white_flower_spruce = true
			golden_apple_acacia = true
			golden_apple_birch = true
			golden_apple_dark_oak = true
			golden_apple_jungle = true
			golden_apple_oak = true
			golden_apple_spruce = true

		[types.leaves_type.would]
			willow = true
			baobab = true
			ebony = true
			fir = true
			pine = true
			cedar = true
			mahogany = true
			palm = true
			maple = true
			aspen = true
			walnut = true

		[types.leaves_type.twilightdelight]
			ironwood = true

#Disables specific entries
[entries]

	[entries.stone_type]

		[entries.stone_type.mcwroofs]
			top_roof = true
			lower_roof = true
			steep_roof = true
			bricks_steep_roof = true
			bricks_roof = true
			bricks_top_roof = true
			upper_steep_roof = true
			upper_lower_roof = true
			attic_roof = true
			bricks_attic_roof = true
			roof = true
			bricks_lower_roof = true
			bricks_upper_steep_roof = true
			bricks_upper_lower_roof = true

		[entries.stone_type.chipped]
			cracked_flat_tiles = true
			weathered = true
			brick_bordered = true
			smooth_inlayed = true
			bordered = true
			cut_column = true
			rough = true
			massive_bricks = true
			tiny_brick_bordered = true
			pointed_dripstone = true
			angry = true
			vertical_cut = true
			cut_blank = true
			blank_carving = true
			flat_tiles = true
			inlayed = true
			trodden = true
			tiled = true
			creeper_carving = true
			tiled_column = true
			eroded = true
			tiled_bordered = true
			vertical_disordered_bricks = true
			sad = true
			unamused = true
			edged_bricks = true
			bricks = true
			layed_bricks = true
			spider_carving = true
			sanded = true
			small_bricks = true
			duh = true
			curly_pillar = true
			carved = true
			pillar = true
			checkered_tiles = true
			smooth_column = true
			fine_pillar = true
			smoothed_double_inlayed = true
			rounded_bricks = true
			overlapping_tiles = true
			pillar_top = true
			loded = true
			thick_inlayed = true
			mini_tiles = true
			crying = true
			runic_carved = true
			stacked_bricks = true
			inscribed = true
			polished = true
			tiny_layered_slabs = true
			cracked_bricks = true
			pillar_bricks = true
			cracked_disordered_bricks = true
			ornate_pillar = true
			simple_pillar = true
			scales = true
			glad = true
			cobbled = true
			tiny_layered_bricks = true
			engraved = true
			offset_bricks = true
			smooth_ringed = true
			etched_bricks = true
			spiraled = true
			prismal_remnants = true
			tiny_bricks = true

		[entries.stone_type.mcwstairs]
			mossy_brick_railing = true
			mossy_brick_balcony = true
			brick_terrace_stairs = true
			brick_railing = true
			brick_balcony = true
			brick_platform = true
			mossy_brick_skyline_stairs = true
			brick_loft_stairs = true
			mossy_brick_loft_stairs = true
			mossy_brick_platform = true
			brick_compact_stairs = true
			mossy_brick_compact_stairs = true
			mossy_brick_bulk_stairs = true
			brick_skyline_stairs = true
			brick_bulk_stairs = true
			mossy_brick_terrace_stairs = true

		[entries.stone_type.mcwbridges]
			mossy_bridge_pier = true
			bridge_pier = true
			balustrade_bricks_bridge = true
			mossy_bridge_stair = true
			balustrade_mossy_bricks_bridge = true
			bridge = true
			mossy_brick_bridge = true
			brick_bridge_stair = true
			brick_bridge = true

		[entries.stone_type.mcwpaths]
			mossy_running_bond = true
			mossy_strewn_rocky_path = true
			running_bond_path = true
			crystal_floor_path = true
			strewn_rocky_path = true
			mossy_flagstone_slab = true
			running_bond_slab = true
			mossy_flagstone_path = true
			crystal_floor_slab = true
			mossy_windmill_weave = true
			mossy_crystal_floor_path = true
			mossy_flagstone = true
			mossy_crystal_floor_slab = true
			windmill_weave_path = true
			running_bond = true
			windmill_weave_slab = true
			mossy_running_bond_path = true
			mossy_running_bond_slab = true
			flagstone = true
			mossy_crystal_floor = true
			mossy_windmill_weave_slab = true
			mossy_windmill_weave_path = true
			flagstone_slab = true
			crystal_floor = true
			flagstone_path = true
			windmill_weave = true

		[entries.stone_type.rechiseled]
			waves_connecting = true
			smooth_large_tiles_connecting = true
			path_connecting = true
			bordered = true
			small_tiles_connecting = true
			bordered_connecting = true
			waves = true
			path = true
			diagonal_bricks_connecting = true
			brick_paving_connecting = true
			brick_pattern_connecting = true
			small_bricks = true
			small_bricks_connecting = true
			rotated_bricks_connecting = true
			rotated_bricks = true
			crushed_connecting = true
			smooth_tiles = true
			brick_pattern = true
			tiles = true
			squares_connecting = true
			crushed = true
			smooth_brick_paving_connecting = true
			slated = true
			squares = true
			smooth_large_tiles = true
			smooth_rotated_bricks = true
			big_tiles_connecting = true
			smooth_brick_paving = true
			diagonal_bricks = true
			big_tiles = true
			smooth_rotated_bricks_connecting = true
			tiles_connecting = true
			brick_paving = true
			smooth_tiles_connecting = true
			small_tiles = true

		[entries.stone_type.create]
			polished_cut_slab = true
			small_brick_stairs = true
			cut_bricks = true
			layered = true
			pillar = true
			polished_cut = true
			small_brick_slab = true
			polished_cut_stairs = true
			cut_wall = true
			cut_brick_slab = true
			small_brick_wall = true
			cut = true
			cut_stairs = true
			small_bricks = true
			cut_brick_wall = true
			cut_brick_stairs = true
			polished_cut_wall = true
			cut_slab = true

		[entries.stone_type.mcwfences]
			grass_topped_wall = true
			railing_wall = true
			modern_wall = true
			brick_railing_gate = true
			modern_brick_wall = true
			railing_gate = true
			railing_brick_wall = true
			pillar_wall = true

		[entries.stone_type.mcwwindows]
			window2 = true
			brick_arrow_slit = true
			brick_gothic = true
			pane_window = true
			four_window = true
			window = true

	[entries.wood_type]

		[entries.wood_type.chipped]
			fine_planks = true
			checkered_trapdoor = true
			tiled_door = true
			center_cut_log = true
			pegged_planks = true
			secret_door = true
			smooth_planks = true
			bared_glass = true
			ornate_bared_glass = true
			hewn_planks = true
			edged_stripped_log = true
			beach_door = true
			fine_vertical_planks = true
			diamond_bordered_glass = true
			distorted_trapdoor = true
			iron_barred_trapdoor = true
			firewood_log = true
			f_sign_stripped_log = true
			layered_stripped_log = true
			whirlwind_planks = true
			large_diamond_glass_pane = true
			mixed_log = true
			framed_planks = true
			square_glass = true
			vined_trapdoor = true
			barrel = true
			detailed_planks = true
			cobweb_trapdoor = true
			barred_trapdoor = true
			airy_trapdoor = true
			patient_stripped_log = true
			pressed_door = true
			planks_panel = true
			solid_trapdoor = true
			boarded_door = true
			meshed_trapdoor = true
			fancy_trapdoor = true
			paper_door = true
			basket_woven_planks = true
			enclosed_planks = true
			flowering_log = true
			k_sign_stripped_log = true
			double_herringbone_planks = true
			sign_stripped_log = true
			crated_planks = true
			knotted_stripped_log = true
			reinforced_log = true
			classic_windowed_trapdoor = true
			wickered_planks = true
			heavy_trapdoor = true
			laced_planks = true
			boxed_planks = true
			reinforced_crate = true
			large_diamond_glass = true
			snowflake_glass_pane = true
			bricky_planks = true
			slotted_trapdoor = true
			bundled_log = true
			polished_planks = true
			ornate_bared_glass_pane = true
			stern_stripped_log = true
			wall_torch = true
			glass_door = true
			paneled_door = true
			leafy_trapdoor = true
			pointless_trapdoor = true
			planks_shavings = true
			d_sign_stripped_log = true
			windowed_trapdoor = true
			tile_windowed_door = true
			golden_barred_trapdoor = true
			overgrown_trapdoor = true
			overgrown_door = true
			windowed_door = true
			classic_trapdoor = true
			circle_glass = true
			torch = true
			screen_door = true
			crossed_planks = true
			cross_laced_planks = true
			railed_planks = true
			planks_mosaic = true
			circle_glass_pane = true
			versailles_planks = true
			wise_stripped_log = true
			planked_log = true
			woven_glass = true
			woven_trapdoor = true
			gated_door = true
			supported_door = true
			line_bared_glass_pane = true
			horizontal_lined_glass_pane = true
			lumpy_stripped_log = true
			line_bared_glass = true
			slanted_planks = true
			edge_cut_log = true
			barred_door = true
			suspicious_trapdoor = true
			chipped_stripped_log = true
			herringbone_planks = true
			vertically_railed_planks = true
			bared_glass_pane = true
			diamond_bordered_glass_pane = true
			tiled_planks = true
			dual_paneled_door = true
			square_glass_pane = true
			overgrown_log = true
			thin_planks = true
			warted_trapdoor = true
			horizontal_lined_glass = true
			l_sign_stripped_log = true
			natural_planks = true
			brick_bond_planks = true
			bordered_glass_pane = true
			sliding_door = true
			bordered_glass = true
			reinforced_stripped_log = true
			shack_door = true
			diagonal_planks = true
			crate = true
			nailed_planks = true
			cornered_planks = true
			shifted_planks = true
			vertical_planks = true
			fortified_door = true
			carved_stripped_log = true
			snowflake_glass = true
			heavy_door = true
			stacked_planks = true
			twisted_trapdoor = true
			i_sign_stripped_log = true
			diamond_planks = true
			woven_glass_pane = true
			damaged_log = true
			nailed_log = true

		[entries.wood_type.mcwroofs]
			top_roof = true
			lower_roof = true
			planks_roof = true
			steep_roof = true
			planks_top_roof = true
			planks_upper_steep_roof = true
			upper_steep_roof = true
			upper_lower_roof = true
			attic_roof = true
			planks_upper_lower_roof = true
			roof = true
			planks_attic_roof = true
			planks_steep_roof = true
			planks_lower_roof = true

		[entries.wood_type.mcwfurnitures]
			stripped_glass_table = true
			end_table = true
			stool_chair = true
			stripped_drawer_counter = true
			stripped_counter = true
			covered_desk = true
			stripped_modern_wardrobe = true
			stripped_covered_desk = true
			stripped_cupboard_counter = true
			stripped_triple_drawer = true
			stripped_chair = true
			stripped_modern_desk = true
			stripped_bookshelf_cupboard = true
			modern_wardrobe = true
			striped_chair = true
			stripped_large_drawer = true
			wardrobe = true
			modern_desk = true
			stripped_end_table = true
			drawer = true
			chair = true
			stripped_table = true
			double_drawer_counter = true
			drawer_counter = true
			counter = true
			table = true
			stripped_double_drawer = true
			lower_triple_drawer = true
			bookshelf = true
			stripped_wardrobe = true
			large_drawer = true
			stripped_desk = true
			stripped_lower_triple_drawer = true
			bookshelf_drawer = true
			double_drawer = true
			stripped_coffee_table = true
			stripped_striped_chair = true
			stripped_stool_chair = true
			cupboard_counter = true
			coffee_table = true
			glass_table = true
			stripped_double_drawer_counter = true
			lower_bookshelf_drawer = true
			stripped_lower_bookshelf_drawer = true
			stripped_bookshelf_drawer = true
			stripped_bookshelf = true
			modern_chair = true
			stripped_modern_chair = true
			bookshelf_cupboard = true
			desk = true
			stripped_double_wardrobe = true
			triple_drawer = true
			double_wardrobe = true
			stripped_drawer = true

		[entries.wood_type.mcwdoors]
			japanese2_door = true
			tropical_door = true
			barn_glass_door = true
			four_panel_door = true
			waffle_door = true
			cottage_door = true
			swamp_door = true
			barn_door = true
			classic_door = true
			beach_door = true
			japanese_door = true
			stable_door = true
			modern_door = true
			nether_door = true
			stable_head_door = true
			western_door = true
			paper_door = true
			bamboo_door = true
			glass_door = true
			mystic_door = true
			bark_glass_door = true

		[entries.wood_type.buildersdelight]
			chair_2 = true
			chair_1 = true
			slab_5 = true
			slab_4 = true
			slab_7 = true
			slab_6 = true
			slab_1 = true
			slab_3 = true
			slab_2 = true
			planks_3 = true
			planks_4 = true
			planks_1 = true
			planks_2 = true
			planks_7 = true
			planks_5 = true
			planks_6 = true
			glass_8 = true
			glass_2 = true
			glass_3 = true
			glass_1 = true
			glass_6 = true
			glass_7 = true
			glass_4 = true
			glass_5 = true
			furniture_kit = true
			stairs_4 = true
			stairs_5 = true
			stairs_6 = true
			stairs_7 = true
			stairs_1 = true
			stairs_2 = true
			frame_7 = true
			stairs_3 = true
			frame_8 = true
			frame_5 = true
			frame_6 = true
			frame_3 = true
			frame_4 = true
			frame_1 = true
			frame_2 = true
			table_1 = true
			table_2 = true
			glass_pane_7 = true
			glass_pane_8 = true
			glass_pane_5 = true
			glass_pane_6 = true
			glass_pane_3 = true
			glass_pane_4 = true
			glass_pane_1 = true
			glass_pane_2 = true

		[entries.wood_type.mcwbridges]
			bridge_pier = true
			rope_bridge = true
			log_bridge_middle = true
			log_bridge_stair = true
			rope_bridge_stair = true
			rail_bridge = true

		[entries.wood_type.mcwtrpdoors]
			swamp_trapdoor = true
			cottage_trapdoor = true
			classic_trapdoor = true
			bamboo_trapdoor = true
			barn_trapdoor = true
			four_panel_trapdoor = true
			barred_trapdoor = true
			ranch_trapdoor = true
			beach_trapdoor = true
			glass_trapdoor = true
			blossom_trapdoor = true
			tropical_trapdoor = true
			paper_trapdoor = true
			bark_trapdoor = true
			mystic_trapdoor = true
			barrel_trapdoor = true

		[entries.wood_type.mcwstairs]
			terrace_stairs = true
			balcony = true
			loft_stairs = true
			railing = true
			skyline_stairs = true
			compact_stairs = true
			platform = true
			bulk_stairs = true

		[entries.wood_type.mcwpaths]
			planks_path = true

		[entries.wood_type.mcwwindows]
			plank_four_window = true
			window2 = true
			stripped_log_window = true
			plank_window2 = true
			louvered_shutter = true
			plank_pane_window = true
			stripped_log_window2 = true
			log_parapet = true
			stripped_log_four_window = true
			plank_window = true
			pane_window = true
			stripped_pane_window = true
			four_window = true
			plank_parapet = true
			blinds = true
			window = true
			shutter = true

		[entries.wood_type.twilightforest]
			hollow_log_climbable = true
			banister = true
			hollow_log_horizontal = true
			hollow_log_vertical = true

		[entries.wood_type.mcwfences]
			picket_fence = true
			wired_fence = true
			pyramid_gate = true
			highley_gate = true
			stockade_fence = true
			horse_fence = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.mcwlights]
			soul_tiki_torch = true
			ceiling_fan_light = true
			tiki_torch = true

		[entries.wood_type.create]
			window_pane = true
			window = true

	[entries.leaves_type]

		[entries.leaves_type.mcwfences]
			hedge = true

