#Tint the enchantment glint in a red shade when the item is enchanted with curses.
#Default Value: true
tint_enchantment_glint_when_cursed = true
#Obfuscate curse enchantments with enchantment runes on item tooltips.
#Default Value: true
obfuscate_curses_on_tooltips = true
#Obfuscate curses on enchanted books.
#Default Value: true
affect_books = true
#Temporarily show curses as normal text while any shift key is held in creative mode.
#Default Value: true
shift_shows_curses_in_creative = true
#Chance wearing or using a cursed piece of equipment will trigger the curses to be revealed. Set to 0.0 to disable revealing curses this way.
#Default Value: 0.05
# Default: 0.05
# Range: 0.0 ~ 1.0
curse_reveal_chance = 0.05
#Amount of experience levels required to make curses on an item visible by combining with an item from the 'sneakycurses:reveal_curses' tag (amethyst shards by default) in an anvil.
#Default Value: 5
# Default: 5
# Range: > 1
material_cost_for_revealing_curses_in_anvil = 5
