<<<<<<< HEAD

=======
>>>>>>> 2778019517a0433caf58eb6181fb0d0fb37a26d4
#Client-side Settings
[client]
	#Determines whether JEI and creative tab will show tinted storage items for iron and higher tiers. Can help with easily removing many of these items from there.
	showHigherTierTintedVariants = true
	#Determines whether JEI and creative tab will show only single wood variant of storage item per tier. Makes creative tab and .
	showSingleWoodVariantOnly = false
<<<<<<< HEAD

=======
>>>>>>> 2778019517a0433caf58eb6181fb0d0fb37a26d4
