<<<<<<< HEAD

=======
>>>>>>> 2778019517a0433caf58eb6181fb0d0fb37a26d4
#Common Settings
[common]
	#Determines whether chests / barrels are always dropped as packed with their contents when broken without the need to use packing tape
	dropPacked = false
<<<<<<< HEAD

=======
>>>>>>> 2778019517a0433caf58eb6181fb0d0fb37a26d4
