#Spice of Life system of lowering food stats when it is being eaten too often
enableSOLModule = true
#Number of eaten foods that will affect food values of next item eaten
# Default: 20
# Range: 1 ~ 1000
historyLength = 20
#You can change hunger formula dependence on circumstances
#Use JavaScript Math module functions for mathematical functions
#Possible inputs: HUNGER, EATEN, SATURATION
hunger = "HUNGER*Math.pow(0.7,EATEN)"
#You can change saturation formula dependence on circumstances
#Use JavaScript Math module functions for mathematical functions
#Possible inputs: HUNGER, EATEN, SATURATION
saturation = "SATURATION*Math.pow(0.7,EATEN)"
#Configured number of exhaustion will be applied constantly
idleExhaustion = true
#The number which will be added to exhaustion each tick
# Default: 0.009999999776482582
# Range: 0.0 ~ 4.0
idleExhaustionQuantity = 0.009999999776482582
#If eating speed affected by food values
modifyFoodEatingSpeed = true
#adds text to GUI describing health and hunger status
addGuiText = true
#Strikes for having low hp
lowHealthStrikes = true
#Strikes for having low hp start at this health level
# Default: 0.25
# Range: 0.05000000074505806 ~ 1.0
healthLevel = 0.20
#Strikes for having low hunger
lowHungerStrikes = true
#Strikes for having low hunger start at this hunger level
# Default: 5
# Range: 1 ~ 20
hungerLevel = 5
#Strikes for having high saturation
highSaturationStrikes = false
#Strikes for having high saturation start at this saturation level
# Default: 15.0
# Range: 0.0 ~ 20.0
saturationLevel = 15.0
#You cannot jump when having extreme strikes
strikesJump = true
#If Nausea effect should be applied
strikesNausea = true
#This value is equal to highest effect amplifier when you have 1 hp/hunger
# Default: 1
# Range: 0 ~ 10
strikesDifficultyBase = 1
#This value will be added to effect amplifier for each difficulty level past PEACEFUL
# Default: 1
# Range: 0 ~ 10
strikesDifficultyScale = 1
#Regeneration rate depends on certain circumstances
regenRework = true
#Regeneration only requires hunger, not saturation
regenHungerOnly = true
#Enable effect which increases regeneration rate
enableWellFed = true
#Makes cake eatable even if it does not give you any benefit
cakeEatableAnyway = false
