[General]
	#Whether or not to set water cauldrons without a purity state to the default purity (set in Thirst config) on chunk load
	#You should only turn this on if there are already cauldrons in your world that are missing a purity state, otherwise there may be significant performance impact for no reason
	#This shouldn't be needed for anything else that stores water; water cauldrons are just unusual since their purity is stored in the blockstate
	"Fix Cauldrons" = false
	#Whether or not to allow drinking from water cauldrons by right-clicking them with an empty hand
	#The amount of thirst/quenchness restored is set in the Thirst config handDrinkingHydration and handDrinkingQuenched, and these values are used even if canDrinkByHand is false
	"Drink Cauldrons" = true
	#The purity of rain water when it fills a cauldron
	# Default: 3
	# Range: 0 ~ 3
	"Rainwater Purity" = 3
	#The purity of water when Pointed Dripstone fills a cauldron
	# Default: 0
	# Range: 0 ~ 3
	"Dripstone Purity" = 0
	#The amount of thirst required to gain a speed bonus
	#If 0, there will be no speed bonus
	# Default: 0
	# Range: 0 ~ 20
	"Thirst Bonus Requirement" = 0
	#The amount of speed bonus to give when the Thirst Bonus Requirement is met
	#This uses the add_multiplied_total operation, so 0.1 = 10% speed increase
	# Default: 0.1
	# Range: 0.0 ~ 1.0
	"Thirst Bonus Value" = 0.1

["Ars Nouveau"]
	#Whether or not the Ars Nouveau Potion Flask should restore thirst when consumed
	"Potion Flasks Restore Thirst" = true
	#Whether or not the Ars Nouveau Potion Flask should pick up water from water source blocks like Glass Bottles
	#Note: Potion flasks, like regular potions, do not store purity, and are always considered 100% pure
	"Potion Flasks Water Blocks" = true
	#Whether or not the Ars Nouveau Potion Flask should pick up water from Cauldrons like Glass Bottles
	"Potion Flasks Cauldron" = true
	#If true, a potion flask's contents can be discarded by shift-right-clicking it in your off hand while your main hand is empty
	"Empty Potion Flasks" = true
	#The capacity of the Ars Nouveau Potion Flask
	#This is the number of potions (or water) it can hold
	#If left at 8, the capacity will not be touched (in case Ars Nouveau makes it configurable in the future)
	#If you change this, you should also change Ars Nouveau's lang file (the keys ars_nouveau.page1.potion_flask and tooltip.potion_flask) to match
	# Default: 8
	# Range: 1 ~ 64
	"Potion Flask Size" = 8

["Ars Elemental"]
	#The purity of the water provided by the Everfull Urn (AKA Urn Of Endless Waters)
	#Water that is bucketed/bottled from, or transferred to a cauldron will have this purity
	#(In other cases, the purity will be the default purity set in the Thirst config)
	# Default: 2
	# Range: 1 ~ 3
	"Everfull Urn Purity" = 2
	#Whether or not water with purity can be taken from the Everfull Urn with bottles and buckets
	#If Potion Flasks Everfull Urn is true, potion flasks will also be able to pick up water from the Everfull Urn
	"Fill from Everfull Urn" = true
	#Whether or not the Flask can be filled from the Everfull Urn
	#Requires Fill from Everfull Urn to be true
	"Fill Flask from Everfull Urn" = true
	#Whether or not filling a bucket/bottle/flask from the Everfull Urn consumes nearby Source
	#Determined by "waterUrnCost" in the Ars Elemental config
	#Requires "Fill from Everfull Urn" to be true
	"Everfull Urn Requests Source" = true

["FTB Ultimine"]
	#The amount of thirst required to use FTB Ultimine
	# Default: 0
	# Range: 0 ~ 20
	"Ultimine Requires Thirst" = 0
